=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/lwpm.schema.json
{
  "title": "JSON schema for configuring LWPM",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://lnmp.khs1994.com",
  "$comment": "https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "description": "see https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "type": "object",
  "definitions": {
    "architecture": {
      "description": "architecture",
      "default": "amd64",
      "type": "string",
      "enum": [
        "arm",
        "arm64",
        "amd64"
      ]
    },
    "os": {
      "description": "os",
      "default": "windows",
      "type": "string",
      "enum": [
        "linux",
        "windows",
        "darwin"
      ]
    },
    "hash": {
      "type": "object",
      "description": "soft package hash",
      "properties": {
        "sha512": {
          "type": "string",
          "description": "sha512 hash"
        },
        "sha256": {
          "type": "string",
          "description": "sha256 hash"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "name": {
      "type": "string",
      "description": "soft name"
    },
    "description": {
      "type": "string",
      "description": "soft description"
    },
    "version": {
      "type": "string",
      "description": "soft version",
      "default": "x.y.z"
    },
    "pre-version": {
      "type": "string",
      "description": "soft pre version",
      "default": "x.y.z-alpha.1"
    },
    "url": {
      "description": "soft download url",
      "type": "string"
    },
    "url-mirror": {
      "description": "soft download url mirror",
      "type": "string"
    },
    "pre-url": {
      "description": "soft pre version download url",
      "type": "string"
    },
    "hash-url": {
      "type": "object",
      "description": "hash url",
      "properties": {
        "sha256": {
          "type": "string",
          "description": "sha256 url"
        },
        "sha384": {
          "type": "string",
          "description": "sha384 url"
        },
        "sha512": {
          "type": "string",
          "description": "sha512 url"
        }
      },
      "additionalProperties": false
    },
    "pre-url-mirror": {
      "description": "soft pre version download url mirror",
      "type": "string"
    },
    "homepage": {
      "description": "soft homepage",
      "type": "string"
    },
    "bug": {
      "description": "soft bug report",
      "type": "string"
    },
    "github": {
      "description": "soft github, example: user/repo",
      "type": "string",
      "default": "username/repo"
    },
    "releases": {
      "description": "soft releases pages",
      "type": "string"
    },
    "architecture": {
      "$ref": "#/definitions/architecture"
    },
    "os": {
      "$ref": "#/definitions/os"
    },
    "platform": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "architecture": {
            "$ref": "#/definitions/architecture"
          },
          "os": {
            "$ref": "#/definitions/os"
          },
          "hash": {
            "$ref": "#/definitions/hash"
          }
        },
        "additionalProperties": false
      },
      "uniqueItems": true,
      "minimum": 1
    },
    "scripts": {
      "type": "object",
      "properties": {
        "platform-reqs": {
          "type": [
            "string",
            "array"
          ],
          "description": "if last command echo $false, means not support this platform. e.g. echo $False",
          "default": [
            "if(!$IsWindows){echo $False}"
          ]
        },
        "preinstall": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "# _cleanup \"$unzipDesc\""
          ]
        },
        "install": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "# Write-Host \"`nPlease download on this website: \\${releases\\}`n\" -ForegroundColor Green",
            "# _unzip \\$filename \\$unzipDesc",
            "# Copy-item -r -force \"\\$unzipDesc/\" \"\"",
            "# cp \\$env:LWPM_PKG_ROOT\\dist\\file \\dest\\path",
            "# Start-Process -FilePath \\$filename -wait",
            "# _cleanup \"\\$unzipDesc\""
          ]
        },
        "postinstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "preuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "uninstall": {
          "type": [
            "string",
            "array"
          ],
          "default": "# _cleanup /soft/path"
        },
        "postuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "pruneuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "pretest": {
          "type": [
            "string",
            "array"
          ]
        },
        "test": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "printInfo $(command --version) install success"
          ]
        },
        "posttest": {
          "type": [
            "string",
            "array"
          ]
        },
        "version": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to get version string"
        },
        "get-latest-version": {
          "type": "string",
          "description": "Function Get-LatestVersion(){ }",
          "default": [
            "Function Get-LatestVersion(){ }"
          ]
        },
        "get-version": {
          "type": "string",
          "description": "set arg $VERSION",
          "default": [
            "if($isPre){$VERSION='x.y.z-beta'}else{$VERSION='x.y.z'}"
          ]
        },
        "hash": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to check soft package hash"
        },
        "dist": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to dist files",
          "default": [
            "# _mkdir \\$env:LWPM_PKG_ROOT/dist",
            "# curl -L `",
            "# \\$url `",
            "# -o \\$env:LWPM_PKG_ROOT/dist/\\${env:lwpm_os\\}-\\${env:lwpm_architecture\\}/\\$filename"
          ]
        }
      },
      "additionalProperties": false
    },
    "path": {
      "type": "array",
      "description": "insert path",
      "items": {
        "type": "string"
      },
      "default": [
        "C:\\bin"
      ]
    },
    "unix-path": {
      "type": "array",
      "description": "unix system(e.g. Linux/macOS) PATH, add to ~/.bashrc manual",
      "items": {
        "type": "string"
      },
      "default": [
        "/path/bin"
      ]
    },
    "command": {
      "type": "string",
      "description": "what command this package provide"
    },
    "download-filename": {
      "type": "string",
      "description": "download filename"
    },
    "$comment": {
      "type": [
        "string",
        "array"
      ],
      "description": "Comments from this package"
    }
  },
  "required": [
    "version"
  ],
  "additionalProperties": false
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/compose/lwpm.json
{
  "name": "compose",
  "platform": [
    {
      "os": "windows",
      "architecture": "amd64"
    },
    {
      "os": "windows",
      "architecture": "arm64"
    },
    {
      "os": "darwin",
      "architecture": "amd64"
    },
    {
      "os": "darwin",
      "architecture": "arm64"
    },
    {
      "os": "linux",
      "architecture": "amd64"
    },
    {
      "os": "linux",
      "architecture": "arm64"
    }
  ],
  "pre-version": "2.17.3",
  "scripts": {
    "dist": "_mkdir $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}\n\nif(${env:lwpm_os} -ne \"windows\"){\n  $url = $url.trim('.exe')\n  $filename = $filename.trim('.exe')\n}\n\ncurl -L `\n$url `\n-o $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}/$filename\n",
    "install": [
      "_mkdir $HOME/.docker/cli-plugins/",
      "Copy-Item -Force $filename $HOME/.docker/cli-plugins/docker-compose$(if($_IsWindows){echo .exe})"
    ],
    "test": "docker compose version",
    "uninstall": "_cleanup $HOME/.docker/cli-plugins/docker-compose$(if($_IsWindows){echo .exe})\n",
    "version": "(docker compose version).split(' ')[3].trim('v')"
  },
  "url": "https://github.com/docker/compose/releases/download/v${VERSION}/docker-compose-${env:lwpm_os}-${env:LWPM_UNAME_M}$(if($_IsWindows){echo .exe})",
  "url-mirror": "https://download.fgit.ml/docker/compose/releases/download/v${VERSION}/docker-compose-${env:lwpm_os}-${env:LWPM_UNAME_M}$(if($_IsWindows){echo .exe})",
  "version": "2.17.3"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/k8s/crictl/lwpm.json
{
  "command": "crictl",
  "name": "crictl",
  "platform": [
    {
      "architecture": "amd64",
      "os": "windows"
    },
    {
      "architecture": "amd64",
      "os": "linux"
    },
    {
      "architecture": "arm64",
      "os": "linux"
    },
    {
      "architecture": "arm",
      "os": "linux"
    }
  ],
  "scripts": {
    "dist": "_mkdir $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}\n\ncurl -L `\n  $url `\n  -o $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}/$filename\n",
    "install": "if($IsWindows){tar -zxf $filename -C C:\\bin}else{sudo tar -zxf $filename -C /usr/local/bin}",
    "platform-reqs": "if($IsMacOs){echo $False}",
    "test": "crictl --version",
    "uninstall": "_cleanup C:\\bin\\crictl.exe",
    "version": "(crictl --version).split(' ')[2].trim('v')"
  },
  "url": "https://github.com/kubernetes-sigs/cri-tools/releases/download/v${VERSION}/crictl-v${VERSION}-${env:lwpm_os}-${env:lwpm_architecture}.tar.gz",
  "url-mirror": "https://${env:GITHUB_MIRROR}/kubernetes-sigs/cri-tools/releases/download/v${VERSION}/crictl-v${VERSION}-${env:lwpm_os}-${env:lwpm_architecture}.tar.gz",
  "version": "1.30.0"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/etcher/lwpm.json
{
  "description": "Flash OS images to SD cards & USB drives, safely and easily.",
  "name": "etcher",
  "scripts": {
    "install": "Start-Process -FilePath $filename -wait",
    "platform-reqs": "if($env:lwpm_os -eq 'linux'){echo $false}"
  },
  "url": "https://github.com/balena-io/etcher/releases/download/v${VERSION}/balenaEtcher-$(if($env:lwpm_os -eq 'windows'){echo Setup-${VERSION}.exe}else{echo ${VERSION.dmg}})",
  "url-mirror": "https://download.fastgit.org/balena-io/etcher/releases/download/v${VERSION}/balenaEtcher-$(if($env:lwpm_os -eq 'windows'){echo Setup-${VERSION}.exe}else{echo ${VERSION.dmg}})",
  "version": "1.5.112"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/vclib/lwpm.json
{
  "name": "vclib",
  "description": "Microsoft Visual C++ Redistributable for Visual Studio 2019",
  "version": "16.2.0",
  "pre-version": "16.2.0",
  "homepage": "https://support.microsoft.com/zh-cn/help/2977003/the-latest-supported-visual-c-downloads",
  "bug": "",
  "github": "",
  "releases": "",
  "url": "https://aka.ms/vs/16/release/VC_redist.x64.exe",
  "$comment": [
    "https://support.microsoft.com/zh-cn/help/2977003/the-latest-supported-visual-c-downloads",
    "https://www.microsoft.com/en-us/download/details.aspx?id=40784"
  ],
  "scripts": {
    "platform-reqs": "if(!$IsWindows){echo $False}",
    "install": [
      "Start-Process -FilePath $filename -wait"
    ]
  }
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/mysql/lwpm.json
{
  "name": "mysql",
  "description": "MySQL Server, the world's most popular open source database, and MySQL Cluster, a real-time, open source transactional database",
  "version": "8.0.20",
  "pre-version": "8.0.20",
  "homepage": "http://www.mysql.com/",
  "bug": "",
  "github": "mysql/mysql-server",
  "releases": "https://github.com/mysql/mysql-server/releases",
  "url": "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${VERSION}-winx64.zip",
  "url-mirror": "https://mirrors.huaweicloud.com/mysql/Downloads/MySQL-8.0/mysql-${VERSION}-winx64.zip"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/k8s/etcd/lwpm.json
{
  "name": "etcd",
  "description": "Distributed reliable key-value store for the most critical data of a distributed system",
  "version": "3.4.16",
  "pre-version": "3.4.16",
  "homepage": "https://etcd.io/",
  "bug": "https://github.com/etcd-io/etcd/issues",
  "github": "etcd-io/etcd",
  "releases": "https://github.com/etcd-io/etcd/releases",
  "url": "https://github.com/etcd-io/etcd/releases/download/v${VERSION}/etcd-v${VERSION}-windows-amd64.zip",
  "url-mirror": "https://mirrors.huaweicloud.com/etcd/v${VERSION}/etcd-v${VERSION}-windows-amd64.zip",
  "command": "etcd",
  "scripts": {
    "install": [
      "_cleanup etcd",
      "_unzip $filename $unzipDesc",
      "Copy-item -r -force etcd\\etcd-v${VERSION}-windows-amd64\\etcd.exe C:\\bin\\",
      "Copy-item -r -force etcd\\etcd-v${VERSION}-windows-amd64\\etcdctl.exe C:\\bin\\",
      "_cleanup etcd"
    ],
    "uninstall": "_cleanup C:\\bin\\etcd.exe C:\\bin\\etcdctl.exe",
    "test": "printInfo $(etcd --version)[0] install success",
    "version": "(etcd --version).split(' ')[2]",
    "hash": [
      "invoke-webrequest https://mirrors.huaweicloud.com/etcd/v${VERSION}/SHA256SUMS -outFile Temp:/etcd-sha256",
      "$hash=(get-content Temp:/etcd-sha256 | select-string $filename).Line.split(' ')[0]",
      "if($hash -and ((Get-SHA256 $filename) -ne $hash)){printError \"$filename sha256 check failed \"}"
    ]
  },
  "path": [
    "C:\\bin"
  ],
  "platform": [
    {
      "os": "windows",
      "architecture": "amd64"
    }
  ]
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/k8s/kubernetes-node/lwpm.json
{
  "name": "kubernetes-node",
  "platform": [
    {
      "architecture": "amd64",
      "os": "linux"
    },
    {
      "architecture": "arm64",
      "os": "linux"
    },
    {
      "architecture": "amd64",
      "os": "windows"
    }
  ],
  "scripts": {
    "platform-reqs": [
      "if($IsMacOs){echo $False}"
    ],
    "dist": "_mkdir $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}\n\ncurl -L `\n  $url `\n  -o $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}/$filename\n"
  },
  "url": "https://storage.googleapis.com/kubernetes-release/release/v${VERSION}/kubernetes-node-${env:lwpm_os}-${env:lwpm_architecture}.tar.gz",
  "version": "1.30.0"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/wechat/lwpm.json
{
  "name": "wechat",
  "description": "Free messaging and calling app",
  "version": "latest",
  "pre-version": "latest",
  "homepage": "https://weixin.qq.com/",
  "bug": "",
  "github": "",
  "releases": "",
  "url": "https://dldir1.qq.com/weixin/$(if($IsMacOs){echo mac/WeChatMac.dmg}else{echo Windows/WeChatSetup.exe})",
  "command": "${env:ProgramFiles}\\Tencent\\WeChat\\WeChat.exe",
  "scripts": {
    "platform-reqs": [
      "if(!($IsWindows -or $IsMacOs)){echo $False}"
    ],
    "install": "Start-Process -FilePath $filename -wait",
    "uninstall": "& ${env:ProgramFiles(x86)}\\Tencent\\WeChat\\Uninstall.exe",
    "version": "echo ${VERSION}",
    "test": "& get-command ${env:ProgramFiles}\\Tencent\\WeChat\\WeChat.exe"
  }
}
