=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/lwpm.schema.json
{
  "title": "JSON schema for configuring LWPM",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://lnmp.khs1994.com",
  "$comment": "https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "description": "see https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "type": "object",
  "definitions": {
    "architecture": {
      "description": "architecture",
      "default": "amd64",
      "type": "string",
      "enum": [
        "arm",
        "arm64",
        "amd64"
      ]
    },
    "os": {
      "description": "os",
      "default": "windows",
      "type": "string",
      "enum": [
        "linux",
        "windows",
        "darwin"
      ]
    },
    "hash": {
      "type": "object",
      "description": "soft package hash",
      "properties": {
        "sha512": {
          "type": "string",
          "description": "sha512 hash"
        },
        "sha256": {
          "type": "string",
          "description": "sha256 hash"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "name": {
      "type": "string",
      "description": "soft name"
    },
    "description": {
      "type": "string",
      "description": "soft description"
    },
    "version": {
      "type": "string",
      "description": "soft version",
      "default": "x.y.z"
    },
    "pre-version": {
      "type": "string",
      "description": "soft pre version",
      "default": "x.y.z-alpha.1"
    },
    "url": {
      "description": "soft download url",
      "type": "string"
    },
    "url-mirror": {
      "description": "soft download url mirror",
      "type": "string"
    },
    "pre-url": {
      "description": "soft pre version download url",
      "type": "string"
    },
    "hash-url": {
      "type": "object",
      "description": "hash url",
      "properties": {
        "sha256": {
          "type": "string",
          "description": "sha256 url"
        },
        "sha384": {
          "type": "string",
          "description": "sha384 url"
        },
        "sha512": {
          "type": "string",
          "description": "sha512 url"
        }
      },
      "additionalProperties": false
    },
    "pre-url-mirror": {
      "description": "soft pre version download url mirror",
      "type": "string"
    },
    "homepage": {
      "description": "soft homepage",
      "type": "string"
    },
    "bug": {
      "description": "soft bug report",
      "type": "string"
    },
    "github": {
      "description": "soft github, example: user/repo",
      "type": "string",
      "default": "username/repo"
    },
    "releases": {
      "description": "soft releases pages",
      "type": "string"
    },
    "architecture": {
      "$ref": "#/definitions/architecture"
    },
    "os": {
      "$ref": "#/definitions/os"
    },
    "platform": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "architecture": {
            "$ref": "#/definitions/architecture"
          },
          "os": {
            "$ref": "#/definitions/os"
          },
          "hash": {
            "$ref": "#/definitions/hash"
          }
        },
        "additionalProperties": false
      },
      "uniqueItems": true,
      "minimum": 1
    },
    "scripts": {
      "type": "object",
      "properties": {
        "platform-reqs": {
          "type": [
            "string",
            "array"
          ],
          "description": "if last command echo $false, means not support this platform. e.g. echo $False",
          "default": [
            "if(!$IsWindows){echo $False}"
          ]
        },
        "preinstall": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "# _cleanup \"$unzipDesc\""
          ]
        },
        "install": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "# Write-Host \"`nPlease download on this website: \\${releases\\}`n\" -ForegroundColor Green",
            "# _unzip \\$filename \\$unzipDesc",
            "# Copy-item -r -force \"\\$unzipDesc/\" \"\"",
            "# cp \\$env:LWPM_PKG_ROOT\\dist\\file \\dest\\path",
            "# Start-Process -FilePath \\$filename -wait",
            "# _cleanup \"\\$unzipDesc\""
          ]
        },
        "postinstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "preuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "uninstall": {
          "type": [
            "string",
            "array"
          ],
          "default": "# _cleanup /soft/path"
        },
        "postuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "pruneuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "pretest": {
          "type": [
            "string",
            "array"
          ]
        },
        "test": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "printInfo $(command --version) install success"
          ]
        },
        "posttest": {
          "type": [
            "string",
            "array"
          ]
        },
        "version": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to get version string"
        },
        "get-latest-version": {
          "type": "string",
          "description": "Function Get-LatestVersion(){ }",
          "default": [
            "Function Get-LatestVersion(){ }"
          ]
        },
        "get-version": {
          "type": "string",
          "description": "set arg $VERSION",
          "default": [
            "if($isPre){$VERSION='x.y.z-beta'}else{$VERSION='x.y.z'}"
          ]
        },
        "hash": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to check soft package hash"
        },
        "dist": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to dist files",
          "default": [
            "# _mkdir \\$env:LWPM_PKG_ROOT/dist",
            "# curl -L `",
            "# \\$url `",
            "# -o \\$env:LWPM_PKG_ROOT/dist/\\${env:lwpm_os\\}-\\${env:lwpm_architecture\\}/\\$filename"
          ]
        }
      },
      "additionalProperties": false
    },
    "path": {
      "type": "array",
      "description": "insert path",
      "items": {
        "type": "string"
      },
      "default": [
        "C:\\bin"
      ]
    },
    "unix-path": {
      "type": "array",
      "description": "unix system(e.g. Linux/macOS) PATH, add to ~/.bashrc manual",
      "items": {
        "type": "string"
      },
      "default": [
        "/path/bin"
      ]
    },
    "command": {
      "type": "string",
      "description": "what command this package provide"
    },
    "download-filename": {
      "type": "string",
      "description": "download filename"
    },
    "$comment": {
      "type": [
        "string",
        "array"
      ],
      "description": "Comments from this package"
    }
  },
  "required": [
    "version"
  ],
  "additionalProperties": false
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/k8s/istioctl/lwpm.json
{
  "command": "istioctl",
  "hash-url": {
    "sha256": "https://github.com/istio/istio/releases/download/${VERSION}/istioctl-${VERSION}-win.zip.sha256"
  },
  "name": "istioctl",
  "scripts": {
    "install": [
      "_unzip $filename C:\\bin\\"
    ],
    "test": "printInfo istioctl $(istioctl version  --remote=false -s) install success",
    "uninstall": "_cleanup C:\\bin\\istioctl.exe",
    "version": "istioctl version  --remote=false -s"
  },
  "url": "https://github.com/istio/istio/releases/download/${VERSION}/istioctl-${VERSION}-win.zip",
  "version": "1.7.0",
  "pre-version": "1.8.0-alpha.2"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/cfssl/lwpm.json
{
  "github": "cloudflare/cfssl",
  "name": "cfssl",
  "path": [
    "C:\\bin"
  ],
  "releases": "https://github.com/cloudflare/cfssl/releases",
  "scripts": {
    "install": "$url = \"https://github.com/cloudflare/cfssl/releases/download/v${VERSION}\"\n$pkgs='cfssl','cfssl-bundle','cfssl-certinfo','cfssl-newkey','cfssl-scan','cfssljson','mkbundle','multirootca'\nforeach($pkg in $pkgs){\n  printInfo Downloading $pkg ...\n\n  if($_isWindows){\n    $dist=\"C:\\bin\\${pkg}.exe\"\n  }else{\n    $dist=\"/usr/local/bin/${pkg}\"\n  }\n\n  if(Test-Path $dist){\n    printTips $pkg exists`, skip\n    continue;\n  }\n\n  if($_isWindows){\n    curl -fsSL $url/${pkg}_${VERSION}_${env:lwpm_os}_amd64$(if($_isWindows){echo .exe}) -o $dist\n  }else{\n    sudo curl -fsSL $url/${pkg}_${VERSION}_${env:lwpm_os}_amd64$(if($_isWindows){echo .exe}) -o $dist\n    sudo chmod +x $dist\n  }\n\n}\n",
    "test": "cfssl version"
  },
  "version": "1.5.0"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/zstd/lwpm.json
{
  "name": "zstd",
  "description": "Zstandard - Fast real-time compression algorithm",
  "version": "1.5.2",
  "pre-version": "1.5.2",
  "homepage": "",
  "bug": "",
  "github": "facebook/zstd",
  "releases": "",
  "url": "https://github.com/facebook/zstd/releases/download/v${VERSION}/zstd-v${VERSION}-win64.zip",
  "url-mirror": "https://download.fastgit.org/facebook/zstd/releases/download/v${VERSION}/zstd-v${VERSION}-win64.zip",
  "pre-url": "",
  "pre-url-mirror": "",
  "command": "zstd",
  "download-filename": "",
  "architecture": "amd64",
  "os": "windows",
  "scripts": {
    "preinstall": [
      ""
    ],
    "install": [
      "_unzip $filename C:\\bin",
      "_cleanup C:\\bin\\zstd",
      "mv C:\\bin\\zstd-v${VERSION}-win64 C:\\bin\\zstd"
    ],
    "postinstall": "",
    "preuninstall": "",
    "uninstall": "_cleanup C:\\bin\\zstd",
    "postuninstall": "",
    "pruneuninstall": "",
    "pretest": "",
    "test": "zstd --version",
    "posttest": "",
    "version": "(zstd --version).split(' ')[6].trim(',').trim('v')"
  },
  "path": [
    "C:\\bin\\zstd"
  ]
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/k8s/helm/lwpm.json
{
  "name": "helm",
  "description": "The Kubernetes Package Manager",
  "version": "3.5.0",
  "pre-version": "3.5.0",
  "homepage": "https://helm.sh/",
  "bug": "https://github.com/helm/helm/issues",
  "github": "helm/helm",
  "releases": "https://github.com/helm/helm/releases",
  "url": "https://get.helm.sh/helm-v${VERSION}-windows-amd64.zip",
  "url-mirror": "https://mirrors.huaweicloud.com/helm/v${VERSION}/helm-v${VERSION}-windows-amd64.zip",
  "command": "helm",
  "scripts": {
    "version": "(ConvertFrom-Json -InputObject (helm version).trim('version.BuildInfo')).Version.trim('v')",
    "test": "printInfo $(helm version) install success",
    "install": [
      "_cleanup helm",
      "_unzip $filename $unzipDesc",
      "Copy-item -r -force helm\\windows-amd64\\helm.exe C:\\bin\\",
      "_cleanup helm"
    ],
    "uninstall": "_cleanup C:\\bin\\helm.exe"
  },
  "path": [
    "C:\\bin"
  ]
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/zeal/lwpm.json
{
  "name": "zeal",
  "description": "Offline documentation browser inspired by Dash",
  "version": "0.6.1",
  "pre-version": "0.6.1",
  "homepage": "https://zealdocs.org/",
  "bug": "https://github.com/zealdocs/zeal/issues",
  "github": "zealdocs/zeal",
  "releases": "https://github.com/zealdocs/zeal/releases",
  "url": "https://github.com/zealdocs/zeal/releases/download/v${VERSION}/zeal-${VERSION}-windows-x64.msi",
  "url-mirror": "https://download.fastgit.org/zealdocs/zeal/releases/download/v${VERSION}/zeal-${VERSION}-windows-x64.msi",
  "command": "${env:ProgramFiles}\\Zeal\\zeal.exe",
  "scripts": {
    "install": "Start-Process -FilePath $filename -wait",
    "test": "ls 'C:\\Program Files\\Zeal\\zeal.exe'",
    "version": "echo ${VERSION}",
    "platform-reqs": [
      "PrintTips Only support windows",
      "echo $True",
      "if(!$IsWindows){echo $False}"
    ]
  }
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/httpd/lwpm.json
{
  "bug": "https://httpd.apache.org/bug_report.html",
  "command": "httpd",
  "description": "",
  "github": "apache/httpd",
  "homepage": "https://httpd.apache.org/",
  "name": "httpd",
  "path": [
    "C:\\Apache24\\bin"
  ],
  "pre-version": "2.4.48",
  "releases": "https://httpd.apache.org/download.cgi",
  "scripts": {
    "install": [
      "$HTTPD_MOD_FCGID_VERSION=\"2.3.10\"\n\n_downloader `\n\"https://www.apachelounge.com/download/VS16/modules/mod_fcgid-${env:HTTPD_MOD_FCGID_VERSION}-win64-VS16.zip\" `\n\"mod_fcgid-${env:HTTPD_MOD_FCGID_VERSION}-win64-VS16.zip\" `\n\"httpd_mod_fcgid\" `\n${env:HTTPD_MOD_FCGID_VERSION}\n",
      "_cleanup $unzipDesc",
      "_unzip $filename $unzipDesc",
      "_mkdir C:\\Apache24",
      "Copy-item -r -force \"httpd\\Apache24\" \"C:\\\"",
      "if (!(Test-Path C:\\Apache24\\modules\\mod_fcgid.so)){\n_unzip mod_fcgid-${env:HTTPD_MOD_FCGID_VERSION}-win64-VS16.zip `\n       mod_fcgid-${env:HTTPD_MOD_FCGID_VERSION}-win64-VS16\n\ncopy-item mod_fcgid-${env:HTTPD_MOD_FCGID_VERSION}-win64-VS16\\mod_fcgid-${env:HTTPD_MOD_FCGID_VERSION}\\mod_fcgid.so `\n          C:\\Apache24\\modules\n\n_cleanup mod_fcgid-${env:HTTPD_MOD_FCGID_VERSION}-win64-VS16\n}\n",
      "$HTTPD_IS_RUN=0",
      "if (!(get-service Apache2.4 -ErrorAction Continue > $null 2>&1)){\n  _sudo httpd -k install\n  $HTTPD_IS_RUN=1\n}\n",
      "_sudo set-service Apache2.4 -StartupType Manual",
      "mkdir $env:USERPROFILE\\lnmp\\windows\\httpd | out-null",
      "mkdir $env:USERPROFILE\\lnmp\\windows\\logs\\httpd | out-null",
      "_ln $env:USERPROFILE\\lnmp\\windows\\httpd C:\\Apache24\\conf.d",
      "_ln $env:USERPROFILE\\lnmp\\windows\\logs\\httpd C:\\Apache24\\logs",
      "_cleanup $unzipDesc"
    ],
    "platform-reqs": "if(!$IsWindows){echo $False}",
    "postinstall": [
      "if ($(Select-String 'IncludeOptional conf.d/' C:\\Apache24\\conf\\httpd.conf).Length -eq 0){ \"==> Add config in C:\\Apache24\\conf\\httpd.conf\"\necho \"`nIncludeOptional conf.d/*.conf `nLoadModule ssl_module modules/mod_ssl.so `nLoadModule headers_module modules/mod_headers.so `nLoadModule socache_shmcb_module modules/mod_socache_shmcb.so \" | out-file -Append C:\\Apache24\\conf\\httpd.conf -Encoding utf8 }"
    ],
    "test": "printInfo $(httpd -v).split(' ')[2] install success",
    "uninstall": [
      "_sudo httpd -k uninstall",
      "_cleanup C:\\Apache24"
    ],
    "version": "($(httpd -v) -split \" \")[2].trim(\"Apache/\")"
  },
  "url": "https://www.apachelounge.com/download/VS16/binaries/httpd-${VERSION}-win64-VS16.zip",
  "version": "2.4.48"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/idea/lwpm.json
{
  "name": "idea",
  "description": "Manage your tools the easy way",
  "version": "2.2.1.19765",
  "pre-version": "2.2.1.19765",
  "homepage": "https://www.jetbrains.com/",
  "bug": "",
  "github": "",
  "releases": "https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains/Toolbox",
  "url": "https://download.jetbrains.com/toolbox/jetbrains-toolbox-${VERSION}.$(if($IsWindows){echo exe}else{echo dmg})",
  "command": "${env:APPDATA}\\..\\Local\\JetBrains\\Toolbox\\bin\\jetbrains-toolbox.exe",
  "scripts": {
    "install": [
      "Start-Process -FilePath $filename -wait"
    ],
    "test": "if($IsWindows){get-command ${env:APPDATA}\\..\\Local\\JetBrains\\Toolbox\\bin\\jetbrains-toolbox.exe}",
    "version": [
      "$version = (get-command ${env:APPDATA}\\..\\Local\\JetBrains\\Toolbox\\bin\\jetbrains-toolbox.exe).Version",
      "${version}.trim('.0')"
    ],
    "platform-reqs": [
      "if($IsLinux){echo $False}"
    ],
    "uninstall": "& $env:APPDATA\\..\\Local\\JetBrains\\Toolbox\\bin\\Uninstall.exe"
  },
  "$comment": [
    "https://www.jetbrains.com/toolbox-app/"
  ]
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/php-cgi-spawner/lwpm.json
{
  "architecture": "amd64",
  "bug": "",
  "command": "",
  "description": "",
  "download-filename": "",
  "github": "deemru/php-cgi-spawner",
  "homepage": "",
  "name": "php-cgi-spawner",
  "os": "windows",
  "path": [
    "C:\\php",
    "C:\\php-pre"
  ],
  "pre-url": "",
  "pre-url-mirror": "",
  "pre-version": "1.1.23",
  "releases": "",
  "scripts": {
    "install": [
      "$PHP_PREFIX='C:/php'\n\nif($isPre -eq 1){\n  $PHP_PREFIX=\"${PHP_PREFIX}-pre\"\n}\n\nif (!(Test-Path \"${PHP_PREFIX}/php.exe\")){\n  printError \"Can't found php on [ $PHP_PREFIX ]\"\n\n  exit 1\n}\n\nGet-Process php-cgi-spawner -ErrorAction \"SilentlyContinue\" | out-null\n\nif($?){\n  printError \"php-cgi-spawner is running, please stop php first\"\n\n  exit 1\n}\n\nprintInfo \"Install php-cgi-spawner on $PHP_PREFIX ...\"\ncp $filename $PHP_PREFIX\n"
    ],
    "platform-reqs": [
      "if(!$IsWindows){echo $False}\n"
    ],
    "postinstall": "",
    "posttest": "",
    "postuninstall": "",
    "preinstall": "",
    "pretest": "",
    "preuninstall": "",
    "pruneuninstall": "",
    "test": "",
    "uninstall": "_cleanup C:\\php\\php-cgi-spawner.exe",
    "version": ""
  },
  "url": "https://github.com/deemru/php-cgi-spawner/releases/download/${VERSION}/php-cgi-spawner.exe",
  "url-mirror": "https://${env:GITHUB_MIRROR}/deemru/php-cgi-spawner/releases/download/${VERSION}/php-cgi-spawner.exe",
  "version": "1.1.23"
}
