=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/lwpm.schema.json
{
  "title": "JSON schema for configuring LWPM",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://lnmp.khs1994.com",
  "$comment": "https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "description": "see https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "type": "object",
  "definitions": {
    "architecture": {
      "description": "architecture",
      "default": "amd64",
      "type": "string",
      "enum": [
        "arm",
        "arm64",
        "amd64"
      ]
    },
    "os": {
      "description": "os",
      "default": "windows",
      "type": "string",
      "enum": [
        "linux",
        "windows",
        "darwin"
      ]
    },
    "hash": {
      "type": "object",
      "description": "soft package hash",
      "properties": {
        "sha512": {
          "type": "string",
          "description": "sha512 hash"
        },
        "sha256": {
          "type": "string",
          "description": "sha256 hash"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "name": {
      "type": "string",
      "description": "soft name"
    },
    "description": {
      "type": "string",
      "description": "soft description"
    },
    "version": {
      "type": "string",
      "description": "soft version",
      "default": "x.y.z"
    },
    "pre-version": {
      "type": "string",
      "description": "soft pre version",
      "default": "x.y.z-alpha.1"
    },
    "url": {
      "description": "soft download url",
      "type": "string"
    },
    "url-mirror": {
      "description": "soft download url mirror",
      "type": "string"
    },
    "pre-url": {
      "description": "soft pre version download url",
      "type": "string"
    },
    "hash-url": {
      "type": "object",
      "description": "hash url",
      "properties": {
        "sha256": {
          "type": "string",
          "description": "sha256 url"
        },
        "sha384": {
          "type": "string",
          "description": "sha384 url"
        },
        "sha512": {
          "type": "string",
          "description": "sha512 url"
        }
      },
      "additionalProperties": false
    },
    "pre-url-mirror": {
      "description": "soft pre version download url mirror",
      "type": "string"
    },
    "homepage": {
      "description": "soft homepage",
      "type": "string"
    },
    "bug": {
      "description": "soft bug report",
      "type": "string"
    },
    "github": {
      "description": "soft github, example: user/repo",
      "type": "string",
      "default": "username/repo"
    },
    "releases": {
      "description": "soft releases pages",
      "type": "string"
    },
    "architecture": {
      "$ref": "#/definitions/architecture"
    },
    "os": {
      "$ref": "#/definitions/os"
    },
    "platform": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "architecture": {
            "$ref": "#/definitions/architecture"
          },
          "os": {
            "$ref": "#/definitions/os"
          },
          "hash": {
            "$ref": "#/definitions/hash"
          }
        },
        "additionalProperties": false
      },
      "uniqueItems": true,
      "minimum": 1
    },
    "scripts": {
      "type": "object",
      "properties": {
        "platform-reqs": {
          "type": [
            "string",
            "array"
          ],
          "description": "if last command echo $false, means not support this platform. e.g. echo $False",
          "default": [
            "if(!$IsWindows){echo $False}"
          ]
        },
        "preinstall": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "# _cleanup \"$unzipDesc\""
          ]
        },
        "install": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "# Write-Host \"`nPlease download on this website: \\${releases\\}`n\" -ForegroundColor Green",
            "# _unzip \\$filename \\$unzipDesc",
            "# Copy-item -r -force \"\\$unzipDesc/\" \"\"",
            "# cp \\$env:LWPM_PKG_ROOT\\dist\\file \\dest\\path",
            "# Start-Process -FilePath \\$filename -wait",
            "# _cleanup \"\\$unzipDesc\""
          ]
        },
        "postinstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "preuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "uninstall": {
          "type": [
            "string",
            "array"
          ],
          "default": "# _cleanup /soft/path"
        },
        "postuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "pruneuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "pretest": {
          "type": [
            "string",
            "array"
          ]
        },
        "test": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "printInfo $(command --version) install success"
          ]
        },
        "posttest": {
          "type": [
            "string",
            "array"
          ]
        },
        "version": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to get version string"
        },
        "get-latest-version": {
          "type": "string",
          "description": "Function Get-LatestVersion(){ }",
          "default": [
            "Function Get-LatestVersion(){ }"
          ]
        },
        "get-version": {
          "type": "string",
          "description": "set arg $VERSION",
          "default": [
            "if($isPre){$VERSION='x.y.z-beta'}else{$VERSION='x.y.z'}"
          ]
        },
        "hash": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to check soft package hash"
        },
        "dist": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to dist files",
          "default": [
            "# _mkdir \\$env:LWPM_PKG_ROOT/dist",
            "# curl -L `",
            "# \\$url `",
            "# -o \\$env:LWPM_PKG_ROOT/dist/\\${env:lwpm_os\\}-\\${env:lwpm_architecture\\}/\\$filename"
          ]
        }
      },
      "additionalProperties": false
    },
    "path": {
      "type": "array",
      "description": "insert path",
      "items": {
        "type": "string"
      },
      "default": [
        "C:\\bin"
      ]
    },
    "unix-path": {
      "type": "array",
      "description": "unix system(e.g. Linux/macOS) PATH, add to ~/.bashrc manual",
      "items": {
        "type": "string"
      },
      "default": [
        "/path/bin"
      ]
    },
    "command": {
      "type": "string",
      "description": "what command this package provide"
    },
    "download-filename": {
      "type": "string",
      "description": "download filename"
    },
    "$comment": {
      "type": [
        "string",
        "array"
      ],
      "description": "Comments from this package"
    }
  },
  "required": [
    "version"
  ],
  "additionalProperties": false
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/mpv/lwpm.json
{
  "name": "mpv",
  "description": "Video player based on MPlayer/mplayer2",
  "version": "0.35.0",
  "pre-version": "20230122-git-92a6f2d",
  "homepage": "https://mpv.io/",
  "bug": "https://mpv.io/bug-reports/",
  "github": "mpv-player/mpv",
  "releases": "https://github.com/mpv-player/mpv/releases",
  "url": "https://downloads.sourceforge.net/project/mpv-player-windows/release/mpv-${VERSION}-x86_64-v3.7z",
  "pre-url": "https://downloads.sourceforge.net/project/mpv-player-windows/64bit-v3/mpv-x86_64-v3-${VERSION}.7z",
  "path": [
    "$env:ProgramData\\mpv"
  ],
  "command": "mpv",
  "scripts": {
    "install": [
      "# https://sourceforge.net/projects/mpv-player-windows/files/",
      "_mkdir ${env:ProgramData}/mpv",
      "powershell -c \"7z x $filename -aoa -r -o${env:ProgramData}/mpv\"",
      "_ln ${env:ProgramData}\\mpv\\mpv.exe $HOME\\Desktop\\mpv.exe"
    ],
    "version": "# (mpv).split()[1]\n echo ${VERSION}",
    "test": "printInfo mpv $((mpv).split()[1]) install success",
    "uninstall": "_cleanup $env:ProgramData\\mpv"
  }
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/k8s/kubernetes-server/lwpm.json
{
  "name": "kubernetes-server",
  "platform": [
    {
      "architecture": "amd64",
      "os": "linux"
    },
    {
      "architecture": "arm64",
      "os": "linux"
    }
  ],
  "scripts": {
    "platform-reqs": [
      "if(!$IsLinux){echo $False}"
    ],
    "dist": "_mkdir $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}\n\ncurl -L `\n  $url `\n  -o $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}/$filename\n"
  },
  "url": "https://storage.googleapis.com/kubernetes-release/release/v${VERSION}/kubernetes-server-${env:lwpm_os}-${env:lwpm_architecture}.tar.gz",
  "version": "1.30.0"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/s6/lwpm.json
{
  "name": "s6",
  "platform": [
    {
      "os": "linux",
      "architecture": "amd64"
    }
  ],
  "scripts": {
    "install": "sudo tar -zxf $filename -C /",
    "platform-reqs": "if(!$_IsLinux){echo $false}"
  },
  "url": "https://github.com/just-containers/s6-overlay/releases/download/v${VERSION}/s6-overlay-x86_64.tar.xz",
  "url-mirror": "https://${env:GITHUB_MIRROR}/just-containers/s6-overlay/releases/download/v${VERSION}/s6-overlay-x86_64.tar.xz",
  "version": "3.1.4.2"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/vim/lwpm.json
{
  "name": "vim",
  "description": "Vi IMproved - enhanced vi editor",
  "version": "8.2.1456",
  "pre-version": "8.2.1456",
  "homepage": "https://www.vim.org/",
  "bug": "https://github.com/vim/vim-win32-installer/issues",
  "github": "vim/vim-win32-installer",
  "releases": "https://github.com/vim/vim-win32-installer/releases",
  "url": "https://github.com/vim/vim-win32-installer/releases/download/v${VERSION}/gvim_${VERSION}_x86.exe",
  "url-mirror": "https://download.fastgit.org/vim/vim-win32-installer/releases/download/v${VERSION}/gvim_${VERSION}_x86.exe",
  "command": "vim",
  "scripts": {
    "platform-reqs": [
      "if(!$IsWindows){echo $False}"
    ],
    "install": [
      "Start-Process -FilePath $filename"
    ],
    "uninstall": [
      "$VERSION_X=(vim --version).split(' ')[4].split('.')[0]",
      "$VERSION_Y=(vim --version).split(' ')[4].split('.')[1]",
      "start-process -wait -path ${env:ProgramFiles(x86)}\\Vim\\vim${VERSION_X}${VERSION_Y}\\uninstall-gui.exe"
    ],
    "test": "printInfo $(vim --version)[0] install success",
    "version": [
      "echo ${VERSION}"
    ]
  }
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/git/lwpm.json
{
  "name": "git",
  "description": "Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency",
  "version": "2.31.1",
  "pre-version": "2.31.1",
  "homepage": "https://git-scm.com/",
  "bug": "https://git-scm.com/community",
  "github": "git/git",
  "releases": "https://github.com/git/git/releases",
  "pre-url" : "",
  "url": "https://github.com/git-for-windows/git/releases/download/v${VERSION}.windows.1/Git-${VERSION}-64-bit.exe",
  "url-mirror":"https://mirrors.huaweicloud.com/git-for-windows/v${VERSION}.windows.1/Git-${VERSION}-64-bit.exe",
  "command": "git",
  "scripts": {
    "platform-reqs": [
      "if(!$IsWindows){echo $False}"
    ],
    "version": "(git --version).split(' ')[2].trim('.1').trim('.windows')",
    "install": [
      "Start-Process -FilePath $filename -wait"
    ],
    "test": "printInfo $(git --version) install success",
    "uninstall": "& $env:ProgramFiles\\Git\\unins001.exe"
  }
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/gpg/lwpm.json
{
  "name": "gpg",
  "description": "",
  "version": "4.3.0",
  "pre-version": "4.3.0",
  "homepage": "https://gnupg.org/",
  "bug": "",
  "github": "gpg/gpg4win",
  "releases": "https://gpg4win.org/download.html",
  "url": "https://files.gpg4win.org/gpg4win-${VERSION}.exe",
  "url-mirror": "",
  "pre-url": "",
  "pre-url-mirror": "",
  "command": "gpg",
  "scripts": {
    "preinstall": "",
    "install": "Start-Process -FilePath $filename -wait",
    "postinstall": "",
    "preuninstall": "",
    "uninstall": "Start-Process -FilePath \"${env:ProgramFiles(x86)}\\Gpg4win\\gpg4win-uninstall\" -Wait",
    "postuninstall": "",
    "pretest": "",
    "test": "printInfo $(gpg --version)[0] install success",
    "posttest":"",
    "version": "(Get-Content ${env:ProgramFiles(x86)}\\Gpg4win\\VERSION)[1]",
    "platform-reqs": [
      "if(!$IsWindows){echo $False}"
    ]
  },
  "path": [
    "${env:ProgramFiles(x86)}\\GnuPG\\bin"
  ]
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/jx/lwpm.json
{
  "command": "jx",
  "url": "https://github.com/jenkins-x/jx/releases/download/v${VERSION}/jx-${env:lwpm_os}-${env:lwpm_architecture}.zip",
  "url-mirror": "https://download.fastgit.org/jenkins-x/jx/releases/download/v${VERSION}/jx-${env:lwpm_os}-${env:lwpm_architecture}.zip",
  "github": "jenkins-x/jx",
  "version": "2.1.33",
  "description": "Jenkins X provides automated CI+CD for Kubernetes with Preview Environments on Pull Requests using Tekton, Knative, Prow, Skaffold and Helm",
  "scripts": {
    "version": "jx --version",
    "install": "_cleanup jx\n\n_unzip $filename jx\n\nCopy-item -r -force \"jx/jx.exe\" C:\\bin\\\n\n_cleanup jx\n",
    "dist": "_mkdir $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}\n\nif(${env:lwpm_os} -ne \"windows\"){\n  $url = $url.trim('zip')\n  $url = \"${url}tar.gz\"\n\n  $filename = $filename.trim('zip')\n  $filename = \"${filename}tar.gz\"\n}\n\ncurl -L $url `\n-o $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}/$filename\n",
    "uninstall": "_cleanup C:\\bin\\jx.exe\n"
  },
  "name": "jx",
  "platform": [
    {
      "architecture": "amd64",
      "os": "windows"
    },
    {
      "architecture": "amd64",
      "os": "darwin"
    },
    {
      "architecture": "amd64",
      "os": "linux"
    },
    {
      "architecture": "arm",
      "os": "linux"
    }
  ],
  "path": [
    "C:\\bin"
  ]
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/helm/lwpm.json
{
  "name": "helm",
  "description": "The Kubernetes Package Manager",
  "version": "3.1.1",
  "pre-version": "3.1.1",
  "homepage": "https://helm.sh/",
  "bug": "https://github.com/helm/helm/issues",
  "github": "helm/helm",
  "releases": "https://github.com/helm/helm/releases",
  "url": "https://get.helm.sh/helm-v${VERSION}-windows-amd64.zip",
  "url-mirror": "https://mirrors.huaweicloud.com/helm/v${VERSION}/helm-v${VERSION}-windows-amd64.zip"
}
